blank_issues_enabled: false

contact_links:
  - name: DVMProject Community (Discord)
    url: https://discord.dvmproject.io/
    about: For questions, discussion, and general support, please join our Discord community.