/**
* Digital Voice Modem - Host Software
* GPLv2 Open Source. Use is subject to license terms.
* DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
*
* @package DVM / Host Software
*
*/
//
// Based on code from the CRUD project. (https://github.com/venediktov/CRUD)
// Licensed under the BPL-1.0 License (https://opensource.org/license/bsl1-0-html)
//
/*
*   Copyright (c) 2003-2013 Christopher M. Kohlhoff
*   Copyright (C) 2023 by Bryan Biedenkapp N2PLL
*
*   Permission is hereby granted, free of charge, to any person or organization
*   obtaining a copy of the software and accompanying documentation covered by
*   this license (the “Software”) to use, reproduce, display, distribute, execute,
*   and transmit the Software, and to prepare derivative works of the Software, and
*   to permit third-parties to whom the Software is furnished to do so, all subject
*   to the following:
*
*   The copyright notices in the Software and this entire statement, including the
*   above license grant, this restriction and the following disclaimer, must be included
*   in all copies of the Software, in whole or in part, and all derivative works of the
*   Software, unless such copies or derivative works are solely in the form of
*   machine-executable object code generated by a source language processor.
*
*   THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
*   INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
*   PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE
*   DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
*   CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
*   OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/
#if !defined(__REST_HTTP__SERVER_CONNECTION_MANAGER_H__)
#define __REST_HTTP__SERVER_CONNECTION_MANAGER_H__

#include "Defines.h"

#include <set>
#include <mutex>

namespace network
{
    namespace rest
    {
        namespace http
        {

            // ---------------------------------------------------------------------------
            //  Class Declaration
            //      Manages open connections so that they may be cleanly stopped when the server
            //      needs to shut down.
            // ---------------------------------------------------------------------------

            template<typename ConnectionPtr>
            class ServerConnectionManager
            {
            public:
                /// <summary>Initializes a new instance of the ServerConnectionManager class.</summary>
                ServerConnectionManager() { /* stub */ }
                /// <summary>Initializes a copy instance of the ServerConnectionManager class.</summary>
                ServerConnectionManager(const ServerConnectionManager&) = delete;

                /// <summary></summary>
                ServerConnectionManager& operator=(const ServerConnectionManager&) = delete;

                /// <summary>Add the specified connection to the manager and start it.</summary>
                void start(ConnectionPtr c)
                {
                    std::lock_guard<std::mutex> guard(m_lock);
                    {
                        m_connections.insert(c);
                    }
                    c->start();
                }

                /// <summary>Stop the specified connection.</summary>
                void stop(ConnectionPtr c)
                {
                    std::lock_guard<std::mutex> guard(m_lock);
                    {
                        m_connections.erase(c);
                    }
                    c->stop();
                }

                /// <summary>Stop all connections.</summary>
                void stopAll()
                {
                    for (auto c : m_connections)
                    c->stop();

                    std::lock_guard<std::mutex> guard(m_lock);
                    m_connections.clear();
                }

            private:
                std::set<ConnectionPtr> m_connections;
                std::mutex m_lock;
            };
        } // namespace http
    } // namespace rest
} // namespace network

#endif // __REST_HTTP__SERVER_CONNECTION_MANAGER_H__
